backend:
  name: github
  repo: diresh-shrestha/OMISSION-Project

media_folder: static/assets
public_folder: assets

collections:
  - label: 'Pages'
    name: 'pages'
    files:
      - label: 'About Page'
        name: 'about'
        file: 'content/About/about.md'
        fields:
          - { label: 'Title', name: 'title', widget: 'string' }

          - {
              label: 'First Paragraph',
              name: 'firstParagraph',
              widget: 'markdown',
            }
          - { label: 'List Item1', name: 'list1', widget: 'markdown' }
          - { label: 'List Item2', name: 'list2', widget: 'markdown' }

          - {
              label: 'Second Paragraph',
              name: 'secondParagraph',
              widget: 'markdown',
            }
          - {
              label: 'Third Paragraph',
              name: 'thirdParagraph',
              widget: 'markdown',
            }
